-- MySQL Script generated by MySQL Workbench
-- Mon Mar 11 12:43:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema culd'ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema culd'ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `culd'ampolla` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincia` (
  `idprovincia` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprovincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localidad` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `id_provincia` INT NOT NULL,
  PRIMARY KEY (`id_localidad`),
  UNIQUE INDEX `id_provincia_UNIQUE` (`id_provincia` ASC) VISIBLE,
  INDEX `id_provincia_idx` (`id_provincia` ASC) VISIBLE,
  CONSTRAINT `id_provincia`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `pizzeria`.`provincia` (`idprovincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`botiga` (
  `idbotiga` INT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `codigo_postal` INT NULL DEFAULT NULL,
  `id_localidad_botiga` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idbotiga`),
  UNIQUE INDEX `id_localidad_UNIQUE` (`id_localidad_botiga` ASC) VISIBLE,
  CONSTRAINT `id_localidad_botiga`
    FOREIGN KEY (`id_localidad_botiga`)
    REFERENCES `pizzeria`.`localidad` (`id_localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(60) NULL DEFAULT NULL,
  `dirección` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_postal` INT NULL DEFAULT NULL,
  `telefono` INT NOT NULL,
  `id_localidad` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `id_localidad_idx` (`id_localidad` ASC) VISIBLE,
  CONSTRAINT `id_localidad`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `pizzeria`.`localidad` (`id_localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `idcategoria` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE,
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `idcategoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `pizzeria`.`categoria` (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`comandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comandas` (
  `idcomanda` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `tipo_entrega` ENUM('domicilio', 'recogida tienda') NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `idproducto` INT NULL DEFAULT NULL,
  `cantidad_producto` INT NULL DEFAULT NULL,
  `idbotiga` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idcomanda`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `idbotiga_UNIQUE` (`idbotiga` ASC) VISIBLE,
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `idproducto_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pizzeria`.`clientes` (`idcliente`),
  CONSTRAINT `idbotiga`
    FOREIGN KEY (`idbotiga`)
    REFERENCES `pizzeria`.`botiga` (`idbotiga`),
  CONSTRAINT `idproducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `pizzeria`.`producto` (`idproducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleats` (
  `idempleat` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(65) NULL DEFAULT NULL,
  `nif` VARCHAR(20) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `id_botiga` INT NULL DEFAULT NULL,
  `rol` ENUM('cuiner', 'repartidor') NULL DEFAULT NULL,
  PRIMARY KEY (`idempleat`),
  INDEX `id_botiga_idx` (`id_botiga` ASC) VISIBLE,
  CONSTRAINT `id_botiga`
    FOREIGN KEY (`id_botiga`)
    REFERENCES `pizzeria`.`botiga` (`idbotiga`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`comandas_repartidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comandas_repartidores` (
  `idcomanda` INT NOT NULL,
  `idempleat` INT NULL DEFAULT NULL,
  `fecha_hora_entrega` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idcomanda`),
  INDEX `idempleat_idx` (`idempleat` ASC) VISIBLE,
  CONSTRAINT `idcomanda`
    FOREIGN KEY (`idcomanda`)
    REFERENCES `pizzeria`.`comandas` (`idcomanda`),
  CONSTRAINT `idempleat`
    FOREIGN KEY (`idempleat`)
    REFERENCES `pizzeria`.`empleats` (`idempleat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `culd'ampolla` ;

-- -----------------------------------------------------
-- Table `culd'ampolla`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culd'ampolla`.`clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `codipostal` VARCHAR(45) NOT NULL,
  `telefon` INT NOT NULL,
  `correo_electronico` VARCHAR(60) NULL DEFAULT NULL,
  `data_registre` DATE NOT NULL,
  `id_cliente_recomendador` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `id_cliente_recomendador_idx` (`id_cliente_recomendador` ASC) VISIBLE,
  CONSTRAINT `id_cliente_recomendador`
    FOREIGN KEY (`id_cliente_recomendador`)
    REFERENCES `culd'ampolla`.`clientes` (`idcliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `culd'ampolla`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culd'ampolla`.`empleats` (
  `idempleat` INT NOT NULL AUTO_INCREMENT,
  `nom_cognoms` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idempleat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `culd'ampolla`.`proveidors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culd'ampolla`.`proveidors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `carrer` VARCHAR(45) NULL DEFAULT NULL,
  `numero` INT NULL DEFAULT NULL,
  `pis` VARCHAR(10) NULL DEFAULT NULL,
  `porta` VARCHAR(10) NULL DEFAULT NULL,
  `ciutat` VARCHAR(45) NULL DEFAULT NULL,
  `codipostal` INT NULL DEFAULT NULL,
  `pais` VARCHAR(25) NULL DEFAULT NULL,
  `telefon` INT NULL DEFAULT NULL,
  `fax` INT NULL DEFAULT NULL,
  `NIF` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `culd'ampolla`.`marques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culd'ampolla`.`marques` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `idproveidor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE,
  INDEX `idproveidor_idx` (`idproveidor` ASC) VISIBLE,
  CONSTRAINT `idproveidor`
    FOREIGN KEY (`idproveidor`)
    REFERENCES `culd'ampolla`.`proveidors` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `culd'ampolla`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culd'ampolla`.`ulleres` (
  `idulleres` INT NOT NULL AUTO_INCREMENT,
  `graduacio_vidres` VARCHAR(45) NULL DEFAULT NULL,
  `tipus_muntura` VARCHAR(45) NULL DEFAULT NULL,
  `color_muntura` VARCHAR(45) NULL DEFAULT NULL,
  `color_vidre` VARCHAR(45) NULL DEFAULT NULL,
  `preu` INT NULL DEFAULT NULL,
  `id_proveidor` INT NULL DEFAULT NULL,
  `id_marca` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idulleres`),
  INDEX `id_proveidors_idx` (`id_proveidor` ASC) VISIBLE,
  INDEX `id_marca_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `id_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `culd'ampolla`.`marques` (`id`),
  CONSTRAINT `id_proveidors`
    FOREIGN KEY (`id_proveidor`)
    REFERENCES `culd'ampolla`.`proveidors` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `culd'ampolla`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culd'ampolla`.`vendas` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NULL DEFAULT NULL,
  `id_ulleres` INT NULL DEFAULT NULL,
  `id_empleat` INT NULL DEFAULT NULL,
  `data_venta` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `id_client_idx` (`id_client` ASC) VISIBLE,
  INDEX `id_ulleres_idx` (`id_ulleres` ASC) VISIBLE,
  INDEX `id_empleat_idx` (`id_empleat` ASC) VISIBLE,
  CONSTRAINT `id_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `culd'ampolla`.`clientes` (`idcliente`),
  CONSTRAINT `id_empleat`
    FOREIGN KEY (`id_empleat`)
    REFERENCES `culd'ampolla`.`empleats` (`idempleat`),
  CONSTRAINT `id_ulleres`
    FOREIGN KEY (`id_ulleres`)
    REFERENCES `culd'ampolla`.`ulleres` (`idulleres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
