-- MySQL Script generated by MySQL Workbench
-- Mon Mar 11 12:39:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincia` (
  `idprovincia` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprovincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localidad` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `id_provincia` INT NOT NULL,
  PRIMARY KEY (`id_localidad`),
  UNIQUE INDEX `id_provincia_UNIQUE` (`id_provincia` ASC) VISIBLE,
  INDEX `id_provincia_idx` (`id_provincia` ASC) VISIBLE,
  CONSTRAINT `id_provincia`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `pizzeria`.`provincia` (`idprovincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`botiga` (
  `idbotiga` INT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `codigo_postal` INT NULL DEFAULT NULL,
  `id_localidad_botiga` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idbotiga`),
  UNIQUE INDEX `id_localidad_UNIQUE` (`id_localidad_botiga` ASC) VISIBLE,
  CONSTRAINT `id_localidad_botiga`
    FOREIGN KEY (`id_localidad_botiga`)
    REFERENCES `pizzeria`.`localidad` (`id_localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(60) NULL DEFAULT NULL,
  `dirección` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_postal` INT NULL DEFAULT NULL,
  `telefono` INT NOT NULL,
  `id_localidad` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `id_localidad_idx` (`id_localidad` ASC) VISIBLE,
  CONSTRAINT `id_localidad`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `pizzeria`.`localidad` (`id_localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `idcategoria` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE,
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `idcategoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `pizzeria`.`categoria` (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`comandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comandas` (
  `idcomanda` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `tipo_entrega` ENUM('domicilio', 'recogida tienda') NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `idproducto` INT NULL DEFAULT NULL,
  `cantidad_producto` INT NULL DEFAULT NULL,
  `idbotiga` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idcomanda`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `idbotiga_UNIQUE` (`idbotiga` ASC) VISIBLE,
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `idproducto_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pizzeria`.`clientes` (`idcliente`),
  CONSTRAINT `idbotiga`
    FOREIGN KEY (`idbotiga`)
    REFERENCES `pizzeria`.`botiga` (`idbotiga`),
  CONSTRAINT `idproducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `pizzeria`.`producto` (`idproducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleats` (
  `idempleat` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(65) NULL DEFAULT NULL,
  `nif` VARCHAR(20) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `id_botiga` INT NULL DEFAULT NULL,
  `rol` ENUM('cuiner', 'repartidor') NULL DEFAULT NULL,
  PRIMARY KEY (`idempleat`),
  INDEX `id_botiga_idx` (`id_botiga` ASC) VISIBLE,
  CONSTRAINT `id_botiga`
    FOREIGN KEY (`id_botiga`)
    REFERENCES `pizzeria`.`botiga` (`idbotiga`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`comandas_repartidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comandas_repartidores` (
  `idcomanda` INT NOT NULL,
  `idempleat` INT NULL DEFAULT NULL,
  `fecha_hora_entrega` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idcomanda`),
  INDEX `idempleat_idx` (`idempleat` ASC) VISIBLE,
  CONSTRAINT `idcomanda`
    FOREIGN KEY (`idcomanda`)
    REFERENCES `pizzeria`.`comandas` (`idcomanda`),
  CONSTRAINT `idempleat`
    FOREIGN KEY (`idempleat`)
    REFERENCES `pizzeria`.`empleats` (`idempleat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
